export const DEMO_PROFILES = [
  {
    id: "demo-1",
    display_name: "Jasmine",
    age: 26,
    bio: "I smell like sunshine and bad decisions. Looking for someone who appreciates a good deodorant... or doesn't.",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&h=300&fit=crop&crop=face",
    scent_category: "Fresh",
    scent_intensity: 2,
    vibe_badges: ["Morning Shower Gang", "Cologne Connoisseur", "Gym Rat"],
    shower_frequency: "Daily",
    last_showered: "2026-05-06",
    scent_preferences: ["Fresh", "Musky"],
    personality_prompts: [
      { prompt: "My signature scent is", answer: "lavender mixed with chaos" },
      { prompt: "The last time I showered was", answer: "this morning, unlike some of you" }
    ],
    location_lat: 40.7128,
    location_lng: -74.006,
    is_online: true,
    last_active: "2026-05-06T14:30:00Z",
    distance: 0.3,
  },
  {
    id: "demo-2",
    display_name: "Marcus",
    age: 29,
    bio: "Yes, I use 3-in-1. No, I will not apologize. My vibes are immaculate even if my hygiene schedule is... creative.",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=face",
    scent_category: "Musky",
    scent_intensity: 4,
    vibe_badges: ["3-in-1 Enthusiast", "Campfire Energy", "Night Owl"],
    shower_frequency: "Every other day",
    scent_preferences: ["Earthy", "Musky"],
    personality_prompts: [
      { prompt: "People say I smell like", answer: "a lumberjack who discovered Axe body spray" },
      { prompt: "My shower playlist is", answer: "nonexistent because I'm speed-running it" }
    ],
    location_lat: 40.715,
    location_lng: -74.002,
    is_online: true,
    last_active: "2026-05-06T14:25:00Z",
    distance: 0.5,
  },
  {
    id: "demo-3",
    display_name: "Luna",
    age: 24,
    bio: "Patchouli princess. I believe in natural body chemistry and the universe. My crystal collection smells better than your cologne.",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&h=300&fit=crop&crop=face",
    scent_category: "Earthy",
    scent_intensity: 3,
    vibe_badges: ["Patchouli Princess", "Crystal Energy", "Yoga Flow"],
    shower_frequency: "When inspired",
    scent_preferences: ["Earthy", "Fresh"],
    personality_prompts: [
      { prompt: "My ideal date smells like", answer: "a farmers market at golden hour" },
      { prompt: "Unpopular opinion:", answer: "deodorant is a scam invented by Big Soap" }
    ],
    location_lat: 40.72,
    location_lng: -73.998,
    is_online: false,
    last_active: "2026-05-06T12:00:00Z",
    distance: 0.8,
  },
  {
    id: "demo-4",
    display_name: "Derek",
    age: 31,
    bio: "I shower twice a day because I respect myself and everyone around me. Looking for someone who appreciates good grooming.",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop&crop=face",
    scent_category: "Fresh",
    scent_intensity: 1,
    vibe_badges: ["Fresh AF", "Skincare Addict", "Twice-a-Day Showerer"],
    shower_frequency: "Daily",
    last_showered: "2026-05-06",
    scent_preferences: ["Fresh", "Neutral"],
    personality_prompts: [
      { prompt: "My medicine cabinet has", answer: "more products than a Sephora" },
      { prompt: "Red flag:", answer: "you think Febreze counts as a shower" }
    ],
    location_lat: 40.708,
    location_lng: -74.01,
    is_online: true,
    last_active: "2026-05-06T14:28:00Z",
    distance: 1.2,
  },
  {
    id: "demo-5",
    display_name: "Sage",
    age: 27,
    bio: "Non-binary icon. I rotate between 47 different perfumes depending on my mood and the position of Mercury.",
    avatar_url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&h=300&fit=crop&crop=face",
    scent_category: "Neutral",
    scent_intensity: 3,
    vibe_badges: ["Perfume Rotator", "Astrology Driven", "Thrift Store Finds"],
    shower_frequency: "Every other day",
    scent_preferences: ["Musky", "Fresh", "Earthy"],
    personality_prompts: [
      { prompt: "My signature scent is", answer: "whatever Mercury is in retrograde for" },
      { prompt: "I'd describe my vibe as", answer: "a candle store had a baby with a music festival" }
    ],
    location_lat: 40.725,
    location_lng: -73.99,
    is_online: false,
    last_active: "2026-05-05T22:00:00Z",
    distance: 1.5,
  },
  {
    id: "demo-6",
    display_name: "Brock",
    age: 33,
    bio: "Just got back from a 3-day music festival. Still haven't showered. Not sorry. My tent, my rules.",
    scent_category: "Ripe",
    scent_intensity: 5,
    vibe_badges: ["Festival Veteran", "No Regrets", "Van Life"],
    shower_frequency: "Weekly",
    scent_preferences: ["Ripe", "Earthy", "Musky"],
    personality_prompts: [
      { prompt: "People say I smell like", answer: "adventure and questionable life choices" },
      { prompt: "The last time I used soap was", answer: "a beautiful memory" }
    ],
    location_lat: 40.73,
    location_lng: -74.005,
    is_online: true,
    last_active: "2026-05-06T14:10:00Z",
    distance: 2.1,
  },
  {
    id: "demo-7",
    display_name: "Priya",
    age: 25,
    bio: "Software engineer by day, incense enthusiast by night. My apartment smells like a temple and I have zero regrets.",
    avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&h=300&fit=crop&crop=face",
    scent_category: "Earthy",
    scent_intensity: 3,
    vibe_badges: ["Incense Queen", "Tech Nerd", "Tea Over Coffee"],
    shower_frequency: "Daily",
    last_showered: "2026-05-06",
    scent_preferences: ["Earthy", "Fresh"],
    personality_prompts: [
      { prompt: "My apartment smells like", answer: "sandalwood and debugging sessions" },
      { prompt: "Deal breaker:", answer: "you judge my incense collection" }
    ],
    location_lat: 40.718,
    location_lng: -73.995,
    is_online: true,
    last_active: "2026-05-06T14:20:00Z",
    distance: 0.9,
  },
  {
    id: "demo-8",
    display_name: "Tyler",
    age: 28,
    bio: "Competitive bodybuilder. I smell like protein shakes and determination. My gym bag has its own zip code.",
    avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&h=300&fit=crop&crop=face",
    scent_category: "Musky",
    scent_intensity: 4,
    vibe_badges: ["Gym Bro", "Protein Powered", "Sweat Equity"],
    shower_frequency: "Daily",
    last_showered: "2026-05-06",
    scent_preferences: ["Fresh", "Musky"],
    personality_prompts: [
      { prompt: "My gym bag smells like", answer: "victory and regret" },
      { prompt: "First date idea:", answer: "couples workout then smoothies (I'm serious)" }
    ],
    location_lat: 40.705,
    location_lng: -74.015,
    is_online: false,
    last_active: "2026-05-06T10:00:00Z",
    distance: 3.4,
  },
];

export const DEMO_CHATS = [
  {
    id: "chat-1",
    partner: DEMO_PROFILES[0],
    lastMessage: "You smell like someone I'd swipe right on 😏",
    timestamp: "2026-05-06T14:20:00Z",
    unread: 2,
  },
  {
    id: "chat-2",
    partner: DEMO_PROFILES[1],
    lastMessage: "Bro my 3-in-1 game is elite, wanna hang?",
    timestamp: "2026-05-06T13:45:00Z",
    unread: 0,
  },
  {
    id: "chat-3",
    partner: DEMO_PROFILES[6],
    lastMessage: "Have you tried sandalwood? Life changing 🪵",
    timestamp: "2026-05-06T12:30:00Z",
    unread: 1,
  },
  {
    id: "chat-4",
    partner: DEMO_PROFILES[3],
    lastMessage: "I just discovered this new moisturizer...",
    timestamp: "2026-05-05T22:00:00Z",
    unread: 0,
  },
];

export const DEMO_MESSAGES = {
  "chat-1": [
    { id: "m1", sender: "them", content: "Hey! Your profile cracked me up 😂", timestamp: "2026-05-06T13:00:00Z" },
    { id: "m2", sender: "me", content: "Haha thanks! I try to keep it real", timestamp: "2026-05-06T13:05:00Z" },
    { id: "m3", sender: "them", content: "So what's your actual signature scent?", timestamp: "2026-05-06T13:10:00Z" },
    { id: "m4", sender: "me", content: "Honestly? Whatever was on sale at Target 😅", timestamp: "2026-05-06T13:15:00Z" },
    { id: "m5", sender: "them", content: "You smell like someone I'd swipe right on 😏", timestamp: "2026-05-06T14:20:00Z" },
  ],
  "chat-2": [
    { id: "m6", sender: "them", content: "What's your take on cologne?", timestamp: "2026-05-06T12:00:00Z" },
    { id: "m7", sender: "me", content: "I mean, one spray is fine. Five is an attack.", timestamp: "2026-05-06T12:05:00Z" },
    { id: "m8", sender: "them", content: "Bro my 3-in-1 game is elite, wanna hang?", timestamp: "2026-05-06T13:45:00Z" },
  ],
  "chat-3": [
    { id: "m9", sender: "them", content: "Namaste! Love your vibe ✨", timestamp: "2026-05-06T11:00:00Z" },
    { id: "m10", sender: "me", content: "Thanks! Your incense collection sounds amazing", timestamp: "2026-05-06T11:30:00Z" },
    { id: "m11", sender: "them", content: "Have you tried sandalwood? Life changing 🪵", timestamp: "2026-05-06T12:30:00Z" },
  ],
  "chat-4": [
    { id: "m12", sender: "them", content: "I just discovered this new moisturizer...", timestamp: "2026-05-05T22:00:00Z" },
  ],
};

export const SCENT_STICKERS = [
  { id: "s1", emoji: "🧼", label: "Fresh & Clean" },
  { id: "s2", emoji: "🌸", label: "Floral Vibes" },
  { id: "s3", emoji: "🔥", label: "Hot Stuff" },
  { id: "s4", emoji: "💨", label: "Wind Check" },
  { id: "s5", emoji: "🧀", label: "Cheesy" },
  { id: "s6", emoji: "🌲", label: "Pine Fresh" },
  { id: "s7", emoji: "🍋", label: "Citrus Pop" },
  { id: "s8", emoji: "💀", label: "RIP Noses" },
  { id: "s9", emoji: "👃", label: "Nose Approved" },
  { id: "s10", emoji: "🤙", label: "Hang Loose" },
  { id: "s11", emoji: "🚿", label: "Shower Time" },
  { id: "s12", emoji: "✨", label: "Sparkling" },
];

export const VIBE_BADGE_CATEGORIES = [
  { emoji: "🌿", name: "Scent Identity", badges: ["Fresh", "Musky", "Earthy", "Ripe", "Smoky", "Sweet", "Spicy", "Herbal", "Woody", "Clean Laundry", "Rainy Day", "Campfire", "Ocean Air"] },
  { emoji: "💪", name: "Lifestyle", badges: ["Gym Rat", "Runner", "Hiker", "Cyclist", "Weightlifter", "Dancer", "Swimmer", "Night Shift", "Office Worker", "Student", "Traveler", "Festival Goer", "Furry"] },
  { emoji: "🌙", name: "Daily Habits", badges: ["Early Bird", "Night Owl", "Coffee Lover", "Tea Lover", "Dog Parent", "Cat Parent", "Gamer", "Bookworm", "Homebody", "Outdoorsy"] },
  { emoji: "🛁", name: "Grooming", badges: ["Daily Shower", "Every Other Day", "Weekly Washer", "Cologne Fan", "Fragrance-Free", "Minimalist", "Skincare Enthusiast"] },
  { emoji: "💬", name: "Personality", badges: ["Introvert", "Extrovert", "Goofy", "Romantic", "Adventurous", "Chill", "Flirty", "Curious", "Hopeless Optimist", "Sarcastic", "Golden Retriever Energy", "Black Cat Energy"] },
  { emoji: "❤️", name: "Looking For", badges: ["Friends", "Dates", "Relationship", "Chat", "Workout Buddy", "Hiking Buddy", "Events", "Local Hangouts"] },
];

export const VIBE_OPTIONS = VIBE_BADGE_CATEGORIES.flatMap((c) => c.badges);

export const FETISH_OPTIONS = [
  "ABDL", "Armpit Worship", "BDSM", "Gags", "Body Hair", "Body Sweat", "Bondage",
  "Butt Plugs", "Chastity", "Choking", "Daddy", "Dominant", "Double Penetration",
  "Edge Play", "Edging", "Exhibitionism", "Feet", "Fisting", "Furry", "Group Play",
  "Hairy Body", "Handler", "Hole Stretching", "Impact Play", "Sloppy Kissing",
  "Latex", "Leather", "Massage", "Worn Underwear", "Oral", "Pet Play", "Photo & Video",
  "Praise", "Public Play", "Puppy Play", "Rimming", "Roleplay", "Rope", "Rubber",
  "Sensory Play", "Servicing", "Sneakers", "Socks", "Spanking", "Spit", "Submissive",
  "Switch", "Taking Orders", "Throat Training", "Uniforms", "Voyeurism", "Wax Play", "Wrestling",
];

export const PERSONALITY_PROMPTS = [
  "My signature scent is",
  "People say I smell like",
  "The last time I showered was",
  "My shower playlist is",
  "My ideal date smells like",
  "My gym bag smells like",
  "Red flag:",
  "Green flag:",
  "Deal breaker:",
  "Unpopular opinion:",
  "My apartment smells like",
  "First date idea:",
  "The last time I used soap was",
  "I'd describe my vibe as",
  "My medicine cabinet has",
];